name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: |
          docker build -t gcr.io/rich-chimera-455016-u7/myapp ./main
          docker push gcr.io/rich-chimera-455016-u7/myapp

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ffxiv-api-app \
            --image gcr.io/rich-chimera-455016-u7/myapp \
            --add-cloudsql-instances rich-chimera-455016-u7:us-central1:root \
            --set-env-vars DB_USER=root,DB_PASS=root6666,DB_NAME=login,DB_SOCKET_PATH=/cloudsql/rich-chimera-455016-u7:us-central1:root \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated

