name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: rich-chimera-455016-u7

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-docker.pkg.dev/rich-chimera-455016-u7/my-repo/myapp ./main
          docker push us-docker.pkg.dev/rich-chimera-455016-u7/my-repo/myapp

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ffxiv-api-app \
            --image us-docker.pkg.dev/rich-chimera-455016-u7/my-repo/myapp \
            --add-cloudsql-instances rich-chimera-455016-u7:us-central1:root \
            --set-env-vars DB_USER=root,DB_PASS=root6666,DB_NAME=login,DB_SOCKET_PATH=/cloudsql/rich-chimera-455016-u7:us-central1:root \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
